const crypto = require('crypto');
function parseMultipart(req, maxBytes=4*1024*1024) { return new Promise((resolve,reject)=>{const chunks=[];let size=0;req.on('data',c=>{size+=c.length;if(size>maxBytes){reject(new Error('Ukuran unggahan melebihi batas.'));req.destroy();return;}chunks.push(c);});req.on('end',()=>{try{const body=Buffer.concat(chunks);const type=req.headers['content-type']||'';const m=type.match(/boundary=(?:(?:"([^"]+)")|([^;]+))/i);if(!m)throw Error('Format unggahan tidak valid.');const boundary=Buffer.from('--'+(m[1]||m[2]));const fields={};let pos=0;while((pos=body.indexOf(boundary,pos))!==-1){pos+=boundary.length;if(body.slice(pos,pos+2).toString()==='--')break;if(body.slice(pos,pos+2).toString()==='\r\n')pos+=2;const headEnd=body.indexOf('\r\n\r\n',pos);if(headEnd<0)break;const headers=body.slice(pos,headEnd).toString();const next=body.indexOf(boundary,headEnd+4);if(next<0)break;const contentEnd=next-2;const disp=headers.match(/content-disposition:\s*form-data;\s*name="([^"]+)"(?:;\s*filename="([^"]*)")?/i);if(disp){const name=disp[1],filename=disp[2],data=body.slice(headEnd+4,contentEnd);if(filename!==undefined){const ct=(headers.match(/content-type:\s*([^\r\n]+)/i)||[])[1]||'application/octet-stream';fields[name]={filename,contentType:ct,buffer:data};}else fields[name]=data.toString('utf8');}pos=next;}resolve(fields);}catch(e){reject(e);}});req.on('error',reject);}); }
function verify(token, secret) { const [body,sig]=String(token||'').split('.');if(!body||!sig)return null;const expected=crypto.createHmac('sha256',secret).update(body).digest();let actual;try{actual=Buffer.from(sig,'base64url')}catch{return null}if(actual.length!==expected.length||!crypto.timingSafeEqual(actual,expected))return null;try{const p=JSON.parse(Buffer.from(body,'base64url').toString());return p.exp>Date.now()?p:null}catch{return null} }
module.exports = async (req,res)=>{
  if(req.method!=='POST')return res.status(405).json({error:'Method tidak diizinkan.'});
  const base=String(process.env.SUPABASE_URL||'').replace(/\/+$/,''),key=process.env.SUPABASE_SERVICE_ROLE_KEY,secret=process.env.REVIEW_TOKEN_SECRET;
  if(!base||!key||!secret)return res.status(503).json({error:'Konfigurasi review server belum lengkap.'});
  let f;try{f=await parseMultipart(req);}catch(e){return res.status(400).json({error:e.message||'File tidak dapat dibaca.'});}
  const payload=verify(f.token,secret);if(!payload)return res.status(401).json({error:'Sesi verifikasi kedaluwarsa. Silakan verifikasi ulang.'});
  const name=String(f.name||'').trim(),body=String(f.body||'').trim(),storeInput=String(f.store_url||'').trim(),rating=Number(f.rating)||5;
  let store=''; if(storeInput){try{const candidate=/^[a-z][a-z0-9+.-]*:\/\//i.test(storeInput)?storeInput:'https://'+storeInput;const u=new URL(candidate);if(!['http:','https:'].includes(u.protocol)||!u.hostname.includes('.'))throw Error();store=u.href;}catch{return res.status(400).json({error:'Link toko/akun harus berupa alamat web yang valid.'});}}
  if(name.length<2||name.length>60||body.length<3||body.length>1000||rating<1||rating>5)return res.status(400).json({error:'Periksa nama, rating, dan isi komentar.'});
  const auth={apikey:key,Authorization:`Bearer ${key}`};
  const orderResponse=await fetch(`${base}/rest/v1/orders?id=eq.${encodeURIComponent(payload.order)}&select=id,customer_whatsapp,payment_status&limit=1`,{headers:auth});
  if(!orderResponse.ok)return res.status(500).json({error:'Database pesanan belum dapat diperiksa.'});
  const [order]=await orderResponse.json();
  const normalize=v=>{let d=String(v||'').replace(/\D/g,'');if(d.startsWith('0'))d='62'+d.slice(1);if(!d.startsWith('62'))d='62'+d;return d;};
  if(!order||!['paid','success','succeeded','completed'].includes(String(order.payment_status||'').toLowerCase())||normalize(order.customer_whatsapp)!==payload.phone)return res.status(403).json({error:'Verifikasi pembayaran tidak lagi valid. Silakan verifikasi ulang.'});
  let photo_url=null, photoPath=null;
  if(f.photo&&f.photo.buffer?.length){const file=f.photo;if(!['image/jpeg','image/png','image/webp'].includes(file.contentType)||file.buffer.length>3*1024*1024)return res.status(400).json({error:'Foto harus JPG, PNG, atau WebP maksimal 3 MB.'});const ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[file.contentType];photoPath=`reviews/${payload.order}-${crypto.randomUUID()}.${ext}`;const upload=await fetch(`${base}/storage/v1/object/review-photos/${photoPath}`,{method:'POST',headers:{...auth,'Content-Type':file.contentType,'x-upsert':'false'},body:file.buffer});if(!upload.ok)return res.status(500).json({error:'Foto gagal disimpan. Coba lagi.'});photo_url=`${base}/storage/v1/object/public/review-photos/${photoPath}`;}
  const insert=await fetch(`${base}/rest/v1/comments`,{method:'POST',headers:{...auth,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify({order_id:payload.order,name,body,rating,store_url:store||null,photo_url,status:'pending',pinned:false})});
  if(!insert.ok){if(photoPath)await fetch(`${base}/storage/v1/object/review-photos/${photoPath}`,{method:'DELETE',headers:auth});if(insert.status===409)return res.status(409).json({error:'Pesanan ini sudah pernah mengirim ulasan.'});return res.status(500).json({error:'Ulasan gagal disimpan. Silakan coba lagi.'});}
  return res.status(200).json({ok:true});
};
